
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 23 12:17:30 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int T_Dato = 18;
  public static final int Coma = 36;
  public static final int Llave_c = 42;
  public static final int Llave_a = 41;
  public static final int Op_Logico = 31;
  public static final int Con_Paso = 17;
  public static final int Fin_Funcion = 22;
  public static final int Repetir = 11;
  public static final int Hasta_Que = 13;
  public static final int Corchete_c = 44;
  public static final int Corchete_a = 43;
  public static final int Fin_Si = 4;
  public static final int Leer = 19;
  public static final int Defecto = 7;
  public static final int P_Coma = 34;
  public static final int Punto = 35;
  public static final int Para = 14;
  public static final int Division = 30;
  public static final int Algoritmo = 25;
  public static final int Cadena = 49;
  public static final int Parentesis_c = 40;
  public static final int Op_Comparacion = 32;
  public static final int Parentesis_a = 39;
  public static final int Segun = 5;
  public static final int Op_Asignacion = 33;
  public static final int Hacer = 16;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Fin_Procedimiento = 24;
  public static final int Funcion = 21;
  public static final int Op_Booleano = 38;
  public static final int Puntos = 37;
  public static final int Caso = 6;
  public static final int ERROR = 50;
  public static final int Entonces = 45;
  public static final int Fin_Mientras = 10;
  public static final int Identificador = 46;
  public static final int Si = 2;
  public static final int Resta = 28;
  public static final int Fin_Segun = 8;
  public static final int Fin_Algoritmo = 26;
  public static final int Sino = 3;
  public static final int Escribir = 20;
  public static final int Mientras = 9;
  public static final int Procedimiento = 23;
  public static final int Multiplicacion = 29;
  public static final int Fin_Para = 15;
  public static final int Numero = 47;
  public static final int Hasta = 12;
  public static final int Suma = 27;
  public static final int Comillas = 48;
}

